# Generated by Django 4.0.1 on 2022-01-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, max_length=10, null=True)),
                ('testname', models.CharField(blank=True, max_length=1000, null=True)),
                ('testcode', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=256, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
