# Generated by Django 4.0.1 on 2022-02-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_coupon_order_refund_payment_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
