# Generated by Django 4.0.1 on 2022-02-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
