# Generated by Django 4.0.1 on 2022-02-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderplaced_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
