# Generated by Django 4.0.1 on 2022-02-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderplaced_amount_orderplaced_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_id',
        ),
    ]
