# Generated by Django 4.0.1 on 2022-02-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paymentdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdone',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
